name: Update Index

on:
  push:
    paths:
      - "documents/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create index
        run: npx morpho-gpt-cli create-index --index PINECONE_TEST_INDEX --dimension 1536 --key PINECONE_API_KEY  --environment PINECONE_ENVIRONMENT --timeout 200000
        env:
          PINECONE_TEST_INDEX: ${{ secrets.PINECONE_TEST_INDEX }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}

      - name: Update index
        run: npx morpho-gpt-cli update-index --index PINECONE_TEST_INDEX --key PINECONE_API_KEY  --environment PINECONE_ENVIRONMENT --openAIApiKey OPENAI_API_KEY --pathDocs "./documents"
        env:
          PINECONE_TEST_INDEX: ${{ secrets.PINECONE_TEST_INDEX }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
