name: Update Index

on:
  push:
    paths:
      - "documents/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create index
        run: npx morpho-gpt-cli createIndex -i ${{ secrets.PINECONE_TEST_INDEX }} -k ${{ secrets.PINECONE_API_KEY }} -e ${{ secrets.PINECONE_ENVIRONMENT }} -d 1536 -t 200000

      - name: Update index
        run: npx morpho-gpt-cli updateIndex -i ${{ secrets.PINECONE_TEST_INDEX }} -k ${{ secrets.PINECONE_API_KEY }} -e ${{ secrets.PINECONE_ENVIRONMENT }} -p "./documents" -a ${{ secrets.OPENAI_API_KEY }}
